# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'TraxyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TraxyApp
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Eureka'
  pod 'GooglePlaces'
  pod 'Kingfisher'

  target 'TraxyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TraxyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
