# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TraxyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TraxyApp
 # pod 'Eureka', '~> 3.0'
  pod 'Eureka', '~> 2.0.0-beta.1'
  pod 'GooglePlacePicker'

  target 'TraxyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TraxyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
